
  CREATE TABLE "C##JL_TOUR"."CITY" 
   (	"LOCATION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CITYNUMBER" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CITY_PK" PRIMARY KEY ("LOCATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



  CREATE TABLE "C##JL_TOUR"."DETAIL" 
   (	"LOCATION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ATTRACTION" VARCHAR2(200 BYTE), 
	"FOOD" VARCHAR2(200 BYTE), 
	"PATH_TOUR" VARCHAR2(200 BYTE), 
	"PATH_FOOD" VARCHAR2(200 BYTE), 
	 CONSTRAINT "PK_ADD" PRIMARY KEY ("ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_LOCATION" FOREIGN KEY ("LOCATION")
	  REFERENCES "C##JL_TOUR"."CITY" ("LOCATION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

